In [2]:
import numpy as np
import pandas as pd
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression, LogisticRegression
from sklearn.metrics import accuracy_score, mean_squared_error

# Numpy basic concepts

In [14]:
a = np.array([10, 20, 30, 40, 50])
b = np.array([1, 2, 3, 4, 5])

res1 = a + b              
res2 = a[a >= 30]     # masking    

print(res1)                
print(res2)                
print(a.sum())             
print(a.min())            
print(a.max()) 
print(np.average(a))

[11 22 33 44 55]
[30 40 50]
150
10
50
30.0


# Bench Marking

# time complexity of numpy 

In [6]:
import time
import numpy as np

data = list(range(1, 100000))

# list comprehension
start = time.time()
res1 = [i**2 for i in data]
end = time.time()
print("List comprehension:", end - start)


# map+function
def square(num):
    return num**2
start = time.time()
res2 = list(map(square, data))
end = time.time()
print("map + function:", end - start)


# map+lambda
start = time.time()
res3 = list(map(lambda x: x**2, data))
end = time.time()
print("map + lambda:", end - start)


# NumPy
arr = np.array(data)
start = time.time()
res4 = arr ** 2
end = time.time()
print("NumPy:", end - start)

List comprehension: 0.013365983963012695
map + function: 0.04218268394470215
map + lambda: 0.04402780532836914
NumPy: 0.0008690357208251953


In [ ]:
hash function     ----------    haskey, hashfunciton, hash table     
dict also store as key values

In [11]:
import numpy as np

data1 = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

data2 = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

# add
add = data1 + data2

# sub
sub = data1 - data2

# quotient
quot = data1 / data2

# dot product
mult =np.dot(data1,data2)

# diagonal elements
diag = np.diag(data1)

# first element of each row
first_col = data1[:, 0]

# sum of first row
sum_first_row = data1[0].sum()

# max of second row
max_second_row = data1[1].max()

# min of third row
min_third_row = data1[2].min()

print("Add:\n", add)
print("Sub:\n", sub)
print("Quot:\n", quot)
print("Mult:\n", mult)
print("Diagonal:", diag)
print("First element of each row:", first_col)
print("Sum of first row:", sum_first_row)
print("Max of second row:", max_second_row)
print("Min of third row:", min_third_row)

Add:
 [[11 22 33]
 [44 55 66]
 [77 88 99]]
Sub:
 [[ -9 -18 -27]
 [-36 -45 -54]
 [-63 -72 -81]]
Quot:
 [[0.1 0.1 0.1]
 [0.1 0.1 0.1]
 [0.1 0.1 0.1]]
Mult:
 [[ 300  360  420]
 [ 660  810  960]
 [1020 1260 1500]]
Diagonal: [1 5 9]
First element of each row: [1 4 7]
Sum of first row: 6
Max of second row: 6
Min of third row: 7


# pandas
